import { stringify } from 'yaml';
const docs:any[]=[];
const add=(kind:string,name:string,spec:any)=>docs.push({apiVersion:'cms.mantle.aotter.net/v2',kind,metadata:{name},spec});
const text=(title:string)=>({type:'string',title});
const money=(title:string)=>({type:'integer',minimum:0,title,'x-mcp-hint':'money-minor'});
const bool=(title:string)=>({type:'boolean',default:false,title});
const schema=(name:string,title:string,properties:any,columns:string[],checks:string[]=[],uniqueIndexes:string[][]=[])=>add('Schema',name,{title,lifecycle:'operational',schema:{type:'object',readOnly:true,additionalProperties:false,required:Object.keys(properties),properties},uiSchema:{list:{primaryField:Object.keys(properties)[0],columns}},checks,uniqueIndexes});
schema('roles','自訂業務角色',{name:text('角色名稱'),request:bool('可請購'),approve:bool('主管核准'),finance:bool('財務覆核／付款'),purchase:bool('建立採購單'),receive:bool('驗收')},['request','approve','finance','purchase','receive'],[],[['name']]);
schema('memberships','部門與業務角色',{subject:text('使用者 ID'),displayName:text('姓名'),department:text('部門'),roleId:text('角色 ID')},['displayName','department','roleId'],[],[['subject']]);
schema('budgets','部門預算',{department:text('部門'),remaining:money('可用預算'),reserved:money('已保留預算')},['remaining','reserved'],['remaining >= 0','reserved >= 0'],[['department']]);
schema('vendors','合格供應商',{name:text('供應商'),active:bool('合格'),bankVerified:bool('銀行資料已覆核')},['active','bankVerified'],[],[['name']]);
schema('requests','請購與採購內控',{title:text('請購項目'),amount:money('金額（新臺幣）'),currency:{type:'string',enum:['TWD'],default:'TWD'},department:text('部門'),requester:text('申請人 ID'),vendorId:text('供應商 ID'),state:{type:'string',title:'流程狀態',oneOf:Object.entries({draft:'草稿',manager_review:'待主管核准',finance_review:'待財務覆核',approved:'已核准',ordered:'已採購',received:'已驗收',paid:'已付款'}).map(([value,title])=>({const:value,title}))},manager:text('主管核准人'),financeApprover:text('財務覆核人'),purchaser:text('採購人'),receiver:text('驗收人'),invoiceAmount:money('發票金額'),purpose:text('用途')},['amount','department','state','manager'],['amount > 0','invoiceAmount >= 0']);
schema('audit','不可直接編輯的稽核軌跡',{requestId:text('請購 ID'),action:text('行為'),actor:text('操作者 ID'),detail:text('內容')},['action','actor','createdAt']);
const input=(properties:any)=>({type:'object',additionalProperties:false,required:Object.keys(properties),properties});
const row={id:text('請購 ID'),expectedVersion:{type:'integer',minimum:1,title:'資料版本'}};
const permission=(flag:string,dept=false)=>`EXISTS (SELECT 1 FROM memberships m JOIN roles r ON r.id = m.roleId WHERE m.subject = auth.uid() AND r.${flag} = true${dept?' AND m.department = requests.department':''})`;
function procedure(name:string,title:string,properties:any,sql:string,scope?:string,collection?:string){
 add('Procedure',name,{title,description:title+'；權限與狀態由後端重新驗證。',input:input(properties),output:{type:'object',required:['results']},requires:{auth:{all:scope?['ctx.user']:[{'ctx.staff':['owner']}]}},...(collection?{uiSchema:{collectionAction:collection}}:{}),handler:{sql}});
 add('Trigger',`${name}-admin`,{source:{kind:'mcp',surface:'staff'},target:{procedure:name}});
 add('Trigger',`${name}-http`,{source:{kind:'http',method:'POST',path:`/api/procedures/${name}`},target:{procedure:name}});
}
const audit=(action:string)=>`INSERT INTO audit (requestId, action, actor, detail) SELECT id, '${action}', auth.uid(), title FROM requests WHERE id = input.id;`;
procedure('create-request','建立請購',{title:text('項目'),amountTwd:{type:'integer',title:'金額（新臺幣元）',minimum:1,maximum:1000000},vendorId:text('供應商 ID'),purpose:{...text('用途'),minLength:5}},`INSERT INTO requests (title,amount,currency,department,requester,vendorId,state,manager,financeApprover,purchaser,receiver,invoiceAmount,purpose) VALUES (input.title,input.amountTwd * 100,'TWD',(SELECT m.department FROM memberships m JOIN roles r ON r.id=m.roleId WHERE m.subject=auth.uid() AND r.request=true),auth.uid(),input.vendorId,'draft','','','','',0,input.purpose) RETURNING id,title,amount,state;`,'request','requests');
procedure('submit-request','送出與保留預算',row,`UPDATE requests SET state = CASE WHEN amount < 1000000 THEN 'approved' ELSE 'manager_review' END WHERE id=input.id AND version=input.expectedVersion AND state='draft' AND requester=auth.uid() AND ${permission('request')} AND EXISTS (SELECT 1 FROM budgets b WHERE b.department=requests.department) RETURNING id,title,amount,state;
UPDATE budgets SET remaining=remaining-(SELECT amount FROM requests WHERE id=input.id),reserved=reserved+(SELECT amount FROM requests WHERE id=input.id) WHERE department=(SELECT department FROM requests WHERE id=input.id);
${audit('submitted')}`,'request');
procedure('approve-manager','主管核准（禁止自批）',row,`UPDATE requests SET manager=auth.uid(),state=CASE WHEN amount >= 10000000 THEN 'finance_review' ELSE 'approved' END WHERE id=input.id AND version=input.expectedVersion AND state='manager_review' AND requester<>auth.uid() AND ${permission('approve',true)} RETURNING id,state,manager;
${audit('manager-approved')}`,'approve');
procedure('approve-finance','十萬元以上財務覆核',row,`UPDATE requests SET financeApprover=auth.uid(),state='approved' WHERE id=input.id AND version=input.expectedVersion AND state='finance_review' AND requester<>auth.uid() AND manager<>auth.uid() AND ${permission('finance')} RETURNING id,state;
${audit('finance-approved')}`,'finance');
procedure('place-order','向合格供應商採購',row,`UPDATE requests SET purchaser=auth.uid(),state='ordered' WHERE id=input.id AND version=input.expectedVersion AND state='approved' AND requester<>auth.uid() AND ${permission('purchase')} AND EXISTS (SELECT 1 FROM vendors v WHERE v.id=requests.vendorId AND v.active=true AND v.bankVerified=true) RETURNING id,state;
${audit('ordered')}`,'purchase');
procedure('receive-goods','驗收（採購人不可兼任）',row,`UPDATE requests SET receiver=auth.uid(),state='received' WHERE id=input.id AND version=input.expectedVersion AND state='ordered' AND purchaser<>auth.uid() AND ${permission('receive',true)} RETURNING id,state;
${audit('received')}`,'receive');
procedure('pay-invoice','三方比對後付款',{...row,invoiceAmountTwd:{type:'integer',title:'發票金額（新臺幣元）',minimum:0,maximum:1000000}},`UPDATE requests SET invoiceAmount=input.invoiceAmountTwd * 100,state='paid' WHERE id=input.id AND version=input.expectedVersion AND state='received' AND input.invoiceAmountTwd * 100=amount AND requester<>auth.uid() AND purchaser<>auth.uid() AND receiver<>auth.uid() AND ${permission('finance')} RETURNING id,state,invoiceAmount;
UPDATE budgets SET reserved=reserved-(SELECT amount FROM requests WHERE id=input.id) WHERE department=(SELECT department FROM requests WHERE id=input.id);
${audit('paid')}`,'finance');
procedure('create-role','新增自訂業務角色',{name:text('角色名稱'),request:bool('請購'),approve:bool('主管核准'),finance:bool('財務'),purchase:bool('採購'),receive:bool('驗收')},`INSERT INTO roles (name,request,approve,finance,purchase,receive) VALUES (input.name,input.request,input.approve,input.finance,input.purchase,input.receive) RETURNING *;`,undefined,'roles');
procedure('configure-role','自訂角色權限',{id:text('角色 ID'),expectedVersion:{type:'integer',minimum:1},name:text('角色名稱'),request:bool('請購'),approve:bool('主管核准'),finance:bool('財務'),purchase:bool('採購'),receive:bool('驗收')},`UPDATE roles SET name=input.name,request=input.request,approve=input.approve,finance=input.finance,purchase=input.purchase,receive=input.receive WHERE id=input.id AND version=input.expectedVersion RETURNING *;`);
procedure('assign-role','指派使用者部門／角色',{id:text('成員 ID'),expectedVersion:{type:'integer',minimum:1},department:text('部門'),roleId:text('角色 ID')},`UPDATE memberships SET department=input.department,roleId=input.roleId WHERE id=input.id AND version=input.expectedVersion AND EXISTS (SELECT 1 FROM roles WHERE id=input.roleId) RETURNING *;`);
add('View','procurement-report',{title:'請購審批與採購總表',surface:'staff',requires:{auth:{all:['ctx.user']}},uiSchema:{list:{columns:['title','amount','department','state','vendor','version'],searchFields:['title'],filterFields:['state','department']}},sql:'SELECT q.id,q.title,q.amount,q.department,q.state,v.name AS vendor,q.version FROM requests q JOIN vendors v ON v.id=q.vendorId ORDER BY q.created_at DESC'});
add('View','audit-report',{title:'內控稽核紀錄',surface:'staff',requires:{auth:{all:[{'ctx.staff':['owner']}]}},uiSchema:{list:{columns:['action','actor','detail','created_at']}},sql:'SELECT id,requestId,action,actor,detail,created_at FROM audit ORDER BY created_at DESC'});
schema('child-items','採購明細',{parentId:text('請購 ID'),title:text('明細名稱'),position:{type:'integer',title:'順序'}},['parentId','position']);
const child=docs.find(d=>d.kind==='Schema'&&d.metadata.name==='child-items').spec;
child.uiSchema.list.columns=['title','position']; child.indexes=[['parentId','position']]; child.schema.readOnly=false; child.schema.properties.parentId['x-mantle-ref']={schema:'requests',field:'id'};
const req=docs.find(d=>d.kind==='Schema'&&d.metadata.name==='requests').spec; req.indexes=[['amount'],['state'],['department']];
schema('notes','行政公告',{title:text('標題'),body:text('內容'),priority:{type:'string',title:'優先度',enum:['normal','urgent'],default:'normal'}},['priority']);
const notes=docs.find(d=>d.kind==='Schema'&&d.metadata.name==='notes').spec; notes.lifecycle='publishing'; delete notes.uiSchema; notes.schema.readOnly=false; notes.indexes=[['priority']]; notes.searchableFields=['title'];
add('Procedure','seed-local',{title:'本地驗收資料匯入',requires:{auth:{all:[{'ctx.staff':['owner']}]}},input:input({collection:{type:'string',enum:['roles','memberships','budgets','vendors','requests','child-items']},rows:{type:'array',minItems:1,maxItems:200,items:{type:'object',required:['id','values'],properties:{id:{type:'string'},values:{type:'object'}}}}}),output:{type:'object',required:['count'],properties:{count:{type:'integer'}}},handler:{ref:'seedLocal'}});
add('Trigger','seed-http',{source:{kind:'http',method:'POST',path:'/api/procedures/seed-local'},target:{procedure:'seed-local'}});
await Bun.write('manifests/procurement.yaml',docs.map(x=>stringify(x)).join('---\n'));
