changelog:
  exclude:
    labels:
      - skip-release-notes
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
        - area:docs
    - title: Dependencies
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
