import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const { version } = JSON.parse(
  readFileSync(resolve(__dirname, "package.json"), "utf8"),
) as { version: string };

/**
 * Admin SPA build. `mantle generate` copies this dist into the
 * consumer's Cloudflare Static Assets directory.
 */
export default defineConfig({
  base: "/_mantle/admin/",
  define: {
    __MANTLE_VERSION__: JSON.stringify(version),
  },
  plugins: [
    react(),
    tailwindcss(),
    serverExportsPlugin(),
  ],
  build: {
    outDir: "./dist",
    emptyOutDir: true,
  },
  resolve: {
    alias: {
      "@": resolve(__dirname, "src"),
    },
  },
});

/**
 * OAuth consent HTML reuses only the small system-token stylesheet;
 * the SPA itself stays in native static files.
 */
function serverExportsPlugin(): Plugin {
  return {
    name: "server-exports",
    apply: "build",
    writeBundle() {
      const dist = resolve(__dirname, "dist");
      const systemTokensCss = readFileSync(
        resolve(__dirname, "src/styles/system-tokens.css"),
        "utf8",
      );
      const banner =
        `// AUTO-GENERATED by vite.config.ts serverExportsPlugin — DO NOT EDIT.\n`;
      writeFileSync(
        resolve(dist, "server.js"),
        `${banner}export const systemTokensCss = ${JSON.stringify(systemTokensCss)};\n`,
      );
      writeFileSync(
        resolve(dist, "server.d.ts"),
        `${banner}export declare const systemTokensCss: string;\n`,
      );
    },
  };
}
