import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { viteSingleFile } from "vite-plugin-singlefile";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const { version } = JSON.parse(
  readFileSync(resolve(__dirname, "package.json"), "utf8"),
) as { version: string };

/**
 * Admin SPA build — emits ONE self-contained `dist/index.html` with
 * JS / CSS / assets all inlined. Platform-agnostic: any adapter
 * (cloudflare, netlify, ...) serves the file as a single string for
 * every URL under `/admin/*` — no `/admin/assets/*` plumbing needed.
 *
 * Trade-off: each cold load fetches the full bundle (no HTTP caching
 * of JS chunks). Acceptable for a 1–2 operator admin tool; revisit
 * if the SPA grows past ~1 MB.
 *
 * Dev workflow (one port, 8787, from a cloned publication starter):
 *   Terminal 1:  pnpm dev
 *   Terminal 2:  pnpm -F @aotter/mantle-admin-ui watch
 *
 * `watch` runs `vite build --watch` so every source edit auto-rebuilds
 * `dist/index.html` + `dist/index-html.js`. wrangler dev sees the
 * workspace dep change and re-bundles the worker. Refresh
 * http://localhost:8787/admin to pick up the change.
 *
 * No proxy / second port — the GitHub OAuth app's callback is bound
 * to :8787 so the auth flow has to live there.
 */
export default defineConfig({
  base: "/admin/",
  define: {
    __MANTLE_VERSION__: JSON.stringify(version),
  },
  plugins: [
    react(),
    tailwindcss(),
    viteSingleFile(),
    inlineIndexHtmlPlugin(),
  ],
  build: {
    outDir: "./dist",
    emptyOutDir: true,
    cssCodeSplit: false,
  },
  resolve: {
    alias: {
      "@": resolve(__dirname, "src"),
    },
  },
});

/**
 * Writes siblings exporting the HTML after Vite has written the
 * inlined bundle. `writeBundle` is the first hook that guarantees
 * `dist/index.html` exists, including in clean parallel CI builds.
 */
function inlineIndexHtmlPlugin(): Plugin {
  return {
    name: "inline-index-html",
    apply: "build",
    writeBundle() {
      const dist = resolve(__dirname, "dist");
      const html = readFileSync(resolve(dist, "index.html"), "utf8");
      const systemTokensCss = readFileSync(
        resolve(__dirname, "src/styles/system-tokens.css"),
        "utf8",
      );
      const escaped = JSON.stringify(html);
      const banner =
        `// AUTO-GENERATED by vite.config.ts inlineIndexHtmlPlugin — DO NOT EDIT.\n` +
        `// Source: dist/index.html\n`;
      writeFileSync(
        resolve(dist, "index-html.js"),
        `${banner}export const indexHtml = ${escaped};\n` +
          `export const systemTokensCss = ${JSON.stringify(systemTokensCss)};\n`,
      );
      writeFileSync(
        resolve(dist, "index-html.d.ts"),
        `${banner}export declare const indexHtml: string;\n` +
          `export declare const systemTokensCss: string;\n`,
      );
    },
  };
}
