import {
  emitTypesFromManifests,
  manifestTypeIdentifier,
  type Diagnostic,
  type LinkedManifestSet,
} from "@aotter/mantle-spec";
import { compileRuntimePlan, type RuntimePlan } from "@aotter/mantle-runtime";

export type EmitMantleModuleRequest = {
  readonly linked: LinkedManifestSet;
  readonly plan?: never;
  readonly namespace?: string;
} | {
  readonly plan: RuntimePlan;
  readonly linked?: never;
  readonly namespace?: string;
};

export type EmitMantleModuleResult =
  | { readonly ok: true; readonly source: string }
  | { readonly ok: false; readonly diagnostics: readonly Diagnostic[] };

const GENERATED_NAMES = new Set([
  "sealRuntimePlan", "RuntimeHandlerFn", "CoreMantleStore", "RuntimePlanData",
  "StoreInsert", "StoreUpdate", "StoreDelete", "StoreSelect",
  "StoreSelectResult", "StoreRow", "StoreWriteResult", "ViewQueryOptions",
  "ViewQueryResult", "Schemas", "Views", "Store", "ViewOptions",
  "HostInsertValues", "CallerInsertValues", "HostWrite", "CallerWrite",
  "CallerStore", "MantleHandlers", "plan",
  "Omit", "Partial", "Pick", "Promise",
]);

export function assertMantleNamespace(namespace: string, label = "namespace"): void {
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(namespace) || GENERATED_NAMES.has(namespace)) {
    throw new Error(`${label} must be a non-reserved TypeScript identifier; got ${JSON.stringify(namespace)}`);
  }
}

/** The generated module carries one sealed plan and type maps keyed by wire names. */
export function emitMantleModule(request: EmitMantleModuleRequest): EmitMantleModuleResult {
  const namespace = request.namespace ?? "Mantle";
  assertMantleNamespace(namespace);
  let plan: RuntimePlan;
  if ("plan" in request && request.plan) {
    plan = request.plan;
  } else {
    const compiled = compileRuntimePlan(request.linked);
    if (!compiled.ok) return { ok: false, diagnostics: compiled.diagnostics };
    plan = compiled.value;
  }

  const schemas = sortedValues(plan.schemas);
  const views = sortedValues(plan.views);
  const procedures = sortedValues(plan.procedures);
  const typeSchemas = "linked" in request && request.linked
    ? request.linked.schemas.map(({ manifest }) => manifest)
    : schemas.map(({ manifest }) => manifest);
  const typeProcedures = "linked" in request && request.linked
    ? request.linked.procedures.map(({ manifest }) => manifest)
    : procedures.map(({ manifest }) => manifest);
  const typeViews = "linked" in request && request.linked
    ? request.linked.views.map(({ manifest }) => manifest)
    : views.map(({ manifest }) => manifest);
  const generatedTypes = emitTypesFromManifests({
    schemas: typeSchemas, procedures: typeProcedures, views: typeViews, namespace,
  }).source.replace(/^\/\/ Generated by `mantle-spec emit-types`\. Do not edit by hand\.\n\n/, "").trimEnd();

  return {
    ok: true,
    source: [
      "// Generated by `mantle generate`. Do not edit by hand.",
      'import { sealRuntimePlan } from "@aotter/mantle/runtime";',
      'import type {',
      '  HandlerContext, HandlerFn as RuntimeHandlerFn, MantleStore as CoreMantleStore, RuntimePlanData,',
      '  StoreInsert, StoreUpdate, StoreDelete, StoreSelect, StoreSelectResult,',
      '  StoreRow, StoreWriteResult, ViewQueryOptions, ViewQueryResult,',
      '} from "@aotter/mantle/runtime";',
      '',
      `export const plan = sealRuntimePlan(${JSON.stringify(plan, null, 2)} as const satisfies RuntimePlanData);`,
      '',
      generatedTypes,
      '',
      'export interface Schemas {',
      ...schemas.map((schema) => `  readonly ${JSON.stringify(schema.name)}: ${namespace}.Entry_${manifestTypeIdentifier(schema.name)};`),
      '}',
      '',
      'type HostInsertValues = {',
      ...schemas.map((schema) => insertValuesLine(schema, false)),
      '}',
      'type CallerInsertValues = {',
      ...schemas.map((schema) => insertValuesLine(schema, true)),
      '}',
      '',
      'export interface Views {',
      ...views.map((view) => {
        const name = view.name;
        const params = view.manifest.spec.params
          ? `${namespace}.ViewParams_${manifestTypeIdentifier(name)}` : 'undefined';
        const required = (view.manifest.spec.params?.required?.length ?? 0) > 0;
        return `  readonly ${JSON.stringify(name)}: { readonly params: ${params}; readonly row: ${namespace}.ViewRow_${manifestTypeIdentifier(name)}; readonly required: ${required} };`;
      }),
      '}',
      '',
      'type ViewOptions<N extends keyof Views> = Pick<ViewQueryOptions, "page" | "show"> &',
      '  (Views[N]["params"] extends undefined ? {} : Views[N]["required"] extends true',
      '    ? { readonly params: Views[N]["params"] } : { readonly params?: Views[N]["params"] });',
      'type HostWrite = { [N in keyof Schemas & string]:',
      '  | (Omit<StoreInsert, "insert" | "values"> & { readonly insert: N; readonly values: HostInsertValues[N] })',
      '  | (Omit<StoreUpdate, "update" | "set"> & { readonly update: N; readonly set: Partial<Schemas[N]> })',
      '  | (Omit<StoreDelete, "delete"> & { readonly delete: N })',
      '}[keyof Schemas & string];',
      'type CallerWrite = { [N in keyof Schemas & string]:',
      '  | (Omit<StoreInsert, "insert" | "values"> & { readonly insert: N; readonly values: CallerInsertValues[N] })',
      '  | (Omit<StoreUpdate, "update" | "set"> & { readonly update: N; readonly set: Partial<Schemas[N]> })',
      '  | (Omit<StoreDelete, "delete"> & { readonly delete: N })',
      '}[keyof Schemas & string];',
      'export type Store = Omit<CoreMantleStore, "as" | "select" | "write" | "view"> & {',
      '  as(ctx: HandlerContext): CallerStore;',
      '  select<N extends keyof Schemas & string>(query: Omit<StoreSelect, "from"> & { readonly from: N }):',
      '    Promise<Omit<StoreSelectResult, "rows"> & { readonly rows: readonly (StoreRow & Partial<Schemas[N]>)[] }>;',
      '  write(ops: readonly HostWrite[]): Promise<readonly StoreWriteResult[]>;',
      '  view<N extends keyof Views & string>(name: N, ...options:',
      '    Views[N]["required"] extends true ? [ViewOptions<N>] : [ViewOptions<N>?]):',
      '    Promise<ViewQueryResult<Views[N]["row"]>>;',
      '};',
      'export type CallerStore = Omit<Store, "as" | "write" | "sweepExpired"> & {',
      '  write(ops: readonly CallerWrite[]): Promise<readonly StoreWriteResult[]>;',
      '};',
      '',
      'export type MantleHandlers<Env = unknown> = {',
      ...handlerContractLines(procedures, namespace),
      '};',
      '',
    ].join('\n'),
  };
}

function insertValuesLine(schema: RuntimePlan["schemas"][string], callerBound: boolean): string {
  const properties = schema.manifest.spec.schema.properties ?? {};
  const filled = [...new Set([
    ...(callerBound ? Object.keys(schema.manifest.spec.scope ?? {}) : []),
    ...Object.entries(properties).flatMap(([name, property]) =>
      Object.hasOwn(property, "default") ? [name] : []),
  ])];
  const key = JSON.stringify(schema.name);
  const base = `Schemas[${key}]`;
  const required = Object.keys(properties).filter((name) => !filled.includes(name));
  const value = filled.length
    ? `${required.length ? `Pick<${base}, ${required.map((name) => JSON.stringify(name)).join(" | ")}> & ` : ""}Partial<Pick<${base}, ${filled.map((name) => JSON.stringify(name)).join(" | ")}>>`
    : base;
  return `  readonly ${key}: ${value};`;
}

function handlerContractLines(
  procedures: readonly RuntimePlan["procedures"][string][],
  namespace: string,
): string[] {
  const handlers = new Map<string, string[]>();
  for (const procedure of procedures) {
    const handler = procedure.manifest.spec.handler;
    if (handler.kind !== "ref") continue;
    const entries = handlers.get(handler.ref) ?? [];
    entries.push(procedure.name);
    handlers.set(handler.ref, entries);
  }
  return [...handlers]
    .sort(([a], [b]) => compareText(a, b))
    .map(([ref, entries]) => {
      const names = entries.map(manifestTypeIdentifier).sort();
      const inputs = names.map((name) => `${namespace}.ProcInput_${name}`).join(" | ");
      const outputs = names.map((name) => `${namespace}.ProcOutput_${name}`).join(" | ");
      return `  readonly ${JSON.stringify(ref)}: RuntimeHandlerFn<${inputs}, ${outputs}, Env, CallerStore>;`;
    });
}

function sortedValues<T extends { readonly name: string }>(
  record: Readonly<Record<string, T>>,
): T[] {
  return Object.values(record).sort((a, b) => compareText(a.name, b.name));
}

function compareText(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}
