import {
  EmitTypesUseCase,
  manifestTypeIdentifier,
  validateDiagnostic,
  type Diagnostic,
  type LinkedManifestSet,
} from "@aotter/mantle-spec";
import { compileRuntimePlan, type RuntimePlan } from "@aotter/mantle-runtime";

export interface EmitMantleModuleRequest {
  readonly linked: LinkedManifestSet;
  readonly namespace?: string;
}

export type EmitMantleModuleResult =
  | { readonly ok: true; readonly source: string }
  | { readonly ok: false; readonly diagnostics: readonly Diagnostic[] };

const GENERATED_NAMES = new Set([
  "BootMantleRuntimeArgs",
  "CoreMantleRuntime",
  "CreateMantleOptions",
  "RuntimePlanData",
  "MantleEntry",
  "MantleFieldValue",
  "MantleHandlers",
  "MantleViewOptions",
  "RuntimeHandlerContext",
  "RuntimeHandlerFn",
  "bindMantle",
  "bootMantleRuntime",
  "createMantle",
  "plan",
  "sealRuntimePlan",
]);

export function assertMantleNamespace(namespace: string, label = "namespace"): void {
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(namespace) || GENERATED_NAMES.has(namespace)) {
    throw new Error(`${label} must be a non-reserved TypeScript identifier; got ${JSON.stringify(namespace)}`);
  }
}

/** Pure TypeScript projection of one linked and compiled Mantle revision. */
export function emitMantleModule(request: EmitMantleModuleRequest): EmitMantleModuleResult {
  const namespace = request.namespace ?? "Mantle";
  assertMantleNamespace(namespace);
  const collision = findIdentifierCollision(request.linked);
  if (collision) return { ok: false, diagnostics: [collision] };
  const compiled = compileRuntimePlan(request.linked);
  if (!compiled.ok) return { ok: false, diagnostics: compiled.diagnostics };
  const plan = compiled.value;

  const schemas = sortedValues(plan.schemas);
  const views = sortedValues(plan.views);
  const procedures = sortedValues(plan.procedures);
  const triggers = sortedValues(plan.triggers);
  const generatedTypes = EmitTypesUseCase.run({ linked: request.linked, namespace }).source
    .replace(/^\/\/ Generated by `mantle-spec emit-types`\. Do not edit by hand\.\n\n/, "")
    .trimEnd();
  const handlerTypes = handlerContractLines(procedures, namespace);

  return {
    ok: true,
    source: [
      "// Generated by `mantle generate`. Do not edit by hand.",
      "import { bootMantleRuntime, sealRuntimePlan } from \"@aotter/mantle/runtime\";",
      "import type {",
      "  BootMantleRuntimeArgs,",
      ...(schemas.length > 0 ? [
        "  EntryDataScalar,",
        "  FindManyEntriesByDataFieldArgs,",
      ] : []),
      "  HandlerContext as RuntimeHandlerContext,",
      "  HandlerFn as RuntimeHandlerFn,",
      "  MantleRuntime as CoreMantleRuntime,",
      ...(schemas.length > 0 ? [
        "  ReadEntriesByDataFieldInArgs,",
        "  ReadEntryByDataFieldArgs,",
        "  ReadEntryBySlugArgs,",
      ] : []),
      "  RuntimePlanData,",
      "} from \"@aotter/mantle/runtime\";",
      ...(schemas.length > 0 ? [
        "import type { Entry as CoreEntry } from \"@aotter/mantle/spec\";",
        "",
        "/** A stored entry whose `data` is the Schema's generated shape. */",
        "export type MantleEntry<TData> = CoreEntry<TData>;",
        "/** Scalar members of one declared Schema field, the only values field reads accept. */",
        "export type MantleFieldValue<TData, F extends keyof TData> = Extract<TData[F], EntryDataScalar>;",
      ] : []),
      "",
      `export const plan = sealRuntimePlan(${JSON.stringify(plan, null, 2)} as const satisfies RuntimePlanData);`,
      "",
      generatedTypes,
      "",
      "export interface MantleViewOptions {",
      "  readonly page?: number;",
      "  readonly show?: number;",
      "  readonly ctx?: RuntimeHandlerContext;",
      "}",
      "",
      "export type MantleHandlers<Env = unknown> = {",
      ...handlerTypes,
      "};",
      "",
      "export type CreateMantleOptions<Env = unknown> =",
      "  Omit<BootMantleRuntimeArgs, \"plan\" | \"handlers\"> & {",
      "    readonly handlers?: MantleHandlers<Env>;",
      "  };",
      "",
      "export async function createMantle<Env = unknown>(options: CreateMantleOptions<Env>) {",
      "  const runtime = await bootMantleRuntime({ ...options, plan });",
      "  return bindMantle(runtime);",
      "}",
      "",
      "export function bindMantle(runtime: CoreMantleRuntime) {",
      "  if (runtime.revision !== plan.semanticFingerprint) {",
      "    throw new Error(`Generated Mantle revision '${plan.semanticFingerprint}' cannot bind runtime revision '${runtime.revision}'.`);",
      "  }",
      "  return {",
      "    runtime,",
      "    entries: {",
      ...schemas.flatMap((schema) => schemaLines(schema.name, namespace, Object.keys(schema.manifest.spec.schema.properties ?? {}))),
      "    },",
      "    views: {",
      ...views.flatMap((view) => viewLines(view.manifest, namespace)),
      "    },",
      "    procedures: {",
      ...procedures.flatMap((procedure) =>
        procedureLines(procedure.manifest.metadata.name, namespace)
      ),
      "    },",
      "    triggers: {",
      ...triggers.map((trigger) =>
        `      ${codegenIdentifier(trigger.name)}: ${JSON.stringify({
          name: trigger.name,
          source: trigger.manifest.spec.source,
          target: trigger.target,
        })} as const,`
      ),
      "    },",
      "  } as const;",
      "}",
      "",
    ].join("\n"),
  };
}

function schemaLines(name: string, namespace: string, fieldNames: readonly string[]): string[] {
  const id = codegenIdentifier(name);
  const data = `${namespace}.Entry_${manifestTypeIdentifier(name)}`;
  // Declared field names only. `keyof` would collapse to `string` whenever the
  // Schema allows additional properties, and an undeclared field has no index.
  const fields = fieldNames.length
    ? [...fieldNames].sort(compareText).map((field) => JSON.stringify(field)).join(" | ")
    : "never";
  const field = `F extends (${fields}) & keyof ${data}`;
  return [
    `      ${id}: {`,
    `        createDraft: (request: Omit<Parameters<CoreMantleRuntime["createDraft"]["execute"]>[0], "collection" | "data"> & { readonly data: ${data} }) =>`,
    `          runtime.createDraft.execute({ ...request, collection: ${JSON.stringify(name)}, data: request.data as unknown as Record<string, unknown> }),`,
    `        get: (request: Omit<Parameters<CoreMantleRuntime["getEntry"]["execute"]>[0], "collection">) =>`,
    `          runtime.getEntry.execute({ ...request, collection: ${JSON.stringify(name)} }),`,
    `        updateDraft: (request: Omit<Parameters<CoreMantleRuntime["updateDraft"]["execute"]>[0], "collection">) =>`,
    `          runtime.updateDraft.execute({ ...request, collection: ${JSON.stringify(name)} }),`,
    `        requestPublish: (request: Omit<Parameters<CoreMantleRuntime["requestPublish"]["execute"]>[0], "collection">) =>`,
    `          runtime.requestPublish.execute({ ...request, collection: ${JSON.stringify(name)} }),`,
    `        unpublish: (request: Omit<Parameters<CoreMantleRuntime["unpublish"]["execute"]>[0], "collection">) =>`,
    `          runtime.unpublish.execute({ ...request, collection: ${JSON.stringify(name)} }),`,
    `        archive: (request: Omit<Parameters<CoreMantleRuntime["archive"]["execute"]>[0], "collection">) =>`,
    `          runtime.archive.execute({ ...request, collection: ${JSON.stringify(name)} }),`,
    `        list: (request: Omit<Parameters<CoreMantleRuntime["listEntries"]["execute"]>[0], "collection"> = {}) =>`,
    `          runtime.listEntries.execute({ ...request, collection: ${JSON.stringify(name)} }),`,
    // Indexed field reads, typed from the Schema (#974). `field` is a key of the
    // generated entry shape and `value` its scalar members, so the indexed path
    // is as easy to reach as \`list\` and the row comes back with typed \`data\`.
    `        readBySlug: (request: Omit<ReadEntryBySlugArgs, "collection">) =>`,
    `          runtime.entries.readBySlug({ ...request, collection: ${JSON.stringify(name)} }) as unknown as Promise<MantleEntry<${data}> | null>,`,
    `        readByDataField: <${field}>(request: Omit<ReadEntryByDataFieldArgs, "collection" | "field" | "value"> & { readonly field: F; readonly value: MantleFieldValue<${data}, F> }) =>`,
    `          runtime.entries.readByDataField({ ...request, collection: ${JSON.stringify(name)} }) as unknown as Promise<MantleEntry<${data}> | null>,`,
    `        readByDataFieldIn: <${field}>(request: Omit<ReadEntriesByDataFieldInArgs, "collection" | "field" | "values"> & { readonly field: F; readonly values: readonly MantleFieldValue<${data}, F>[] }) =>`,
    `          runtime.entries.readByDataFieldIn({ ...request, collection: ${JSON.stringify(name)} }) as unknown as Promise<readonly MantleEntry<${data}>[]>,`,
    `        findManyByDataField: <${field}>(request: Omit<FindManyEntriesByDataFieldArgs, "collection" | "field" | "value"> & { readonly field: F; readonly value: MantleFieldValue<${data}, F> }) =>`,
    `          runtime.entries.findManyByDataField({ ...request, collection: ${JSON.stringify(name)} }) as unknown as Promise<readonly MantleEntry<${data}>[]>,`,
    `        delete: (request: Omit<Parameters<CoreMantleRuntime["deleteEntry"]["execute"]>[0], "collection">) =>`,
    `          runtime.deleteEntry.execute({ ...request, collection: ${JSON.stringify(name)} }),`,
    "      },",
  ];
}

function viewLines(
  view: RuntimePlan["views"][string]["manifest"],
  namespace: string,
): string[] {
  const name = view.metadata.name;
  const requiredParams = (view.spec.params?.required?.length ?? 0) > 0;
  const requestType = view.spec.params
    ? `MantleViewOptions & { readonly params${requiredParams ? "" : "?"}: ${namespace}.ViewParams_${manifestTypeIdentifier(name)} }`
    : "MantleViewOptions";
  return [
    `      ${codegenIdentifier(name)}: (request: ${requestType}${requiredParams ? "" : " = {}"}) =>`,
    `        runtime.executeView<${namespace}.ViewRow_${manifestTypeIdentifier(name)}>({`,
    `          view: ${JSON.stringify(name)},`,
    "          ctx: request.ctx,",
    "          options: {",
    ...(view.spec.params ? ["            params: request.params,"] : []),
    "            page: request.page,",
    "            show: request.show,",
    "          },",
    "        }),",
  ];
}

function procedureLines(name: string, namespace: string): string[] {
  const typeId = manifestTypeIdentifier(name);
  return [
    `      ${codegenIdentifier(name)}: (input: ${namespace}.ProcInput_${typeId}, ctx: RuntimeHandlerContext) =>`,
    `        runtime.invokeProcedure<${namespace}.ProcOutput_${typeId}>({`,
    `          procedure: ${JSON.stringify(name)},`,
    "          input,",
    "          ctx,",
    "        }),",
  ];
}

function handlerContractLines(
  procedures: readonly RuntimePlan["procedures"][string][],
  namespace: string,
): string[] {
  const handlers = new Map<string, string[]>();
  for (const procedure of procedures) {
    const handler = procedure.manifest.spec.handler;
    if (handler.kind !== "ref") continue;
    const entries = handlers.get(handler.ref) ?? [];
    entries.push(procedure.name);
    handlers.set(handler.ref, entries);
  }
  return [...handlers]
    .sort(([a], [b]) => compareText(a, b))
    .map(([ref, entries]) => {
      const names = entries.map(manifestTypeIdentifier).sort();
      const inputs = names.map((name) => `${namespace}.ProcInput_${name}`).join(" | ");
      const outputs = names.map((name) => `${namespace}.ProcOutput_${name}`).join(" | ");
      return `  readonly ${JSON.stringify(ref)}: RuntimeHandlerFn<${inputs}, ${outputs}, Env>;`;
    });
}

function findIdentifierCollision(linked: LinkedManifestSet): Diagnostic | undefined {
  const groups = [
    ["entries", linked.schemas],
    ["views", linked.views],
    ["procedures", linked.procedures],
    ["triggers", linked.triggers],
  ] as const;
  for (const [group, entries] of groups) {
    const seen = new Map<string, string>();
    for (const entry of [...entries].sort((a, b) =>
      compareText(a.manifest.metadata.name, b.manifest.metadata.name)
    )) {
      const name = entry.manifest.metadata.name;
      const identifier = codegenIdentifier(name);
      const first = seen.get(identifier);
      if (!first) {
        seen.set(identifier, name);
        continue;
      }
      const source = { ...entry.source, path: "/metadata/name" };
      return validateDiagnostic({
        code: "CODEGEN_IDENTIFIER_COLLISION",
        severity: "error",
        path: `${source.sourceId}#/${source.documentIndex}/metadata/name`,
        source,
        value: name,
        expected: `a ${group} wire name with a unique lower-camel identifier`,
        candidates: [first, name],
        message: `${group} wire names '${first}' and '${name}' both generate '${identifier}'.`,
      });
    }
  }
  return undefined;
}

function sortedValues<T extends { readonly name: string }>(
  record: Readonly<Record<string, T>>,
): T[] {
  return Object.values(record).sort((a, b) => compareText(a.name, b.name));
}

function compareText(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function codegenIdentifier(name: string): string {
  const words = name.match(/[A-Za-z0-9]+/g) ?? [];
  const joined = words.map((word, index) =>
    index === 0
      ? word[0]!.toLowerCase() + word.slice(1)
      : word[0]!.toUpperCase() + word.slice(1)
  ).join("");
  return /^[A-Za-z_$]/.test(joined) ? joined : `_${joined}`;
}
