/**
 * `.mantle/generated/mantle.ts` (ADR-0032 amendment "mantle generate"): the plan from `plan.json`, the `emit-types`
 * namespace, and a typed Store and `MantleHandlers` over exactly this plan. Types only, apart from the `plan` import.
 */
import { emitTypesFromManifests, manifestTypeIdentifier, type LinkedManifestSet, type PlanSchema, type PlanView, type RuntimePlan } from "../spec/index.js";

const NS = "Mantle";
const byName = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);
const key = (s: string) => JSON.stringify(s);

/** What `SELECT *` expands to (policy's `starCols`): the declared fields but the scope field, a geo field as its two columns. */
const starCols = (s: PlanSchema) => Object.entries(s.fields).filter(([f]) => f !== s.scope).flatMap(([f, t]) => (t === "geo" ? [`${f}_lat`, `${f}_lng`] : [f]));

/**
 * A View row's keys, read off the compiled SELECT: an output's `AS` name, else its column's name, and `*` as the Schema's
 * declared fields. Values stay `unknown`: `store.view` returns the storage encoding (lower-case keys, 0/1 booleans, JSON
 * text, microsecond timestamps), not the Schema's JSON shape. Undefined (the row stays `unknown`) when an output has
 * no name, or a `*` reads a subquery or `json_each`.
 */
function viewRowKeys(view: PlanView, schemas: RuntimePlan["schemas"]): string[] | undefined {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sel: any = view.stmts[0]?.SelectStmt;
  if (!sel?.targetList) return undefined;
  const rels = new Map<string, PlanSchema | undefined>();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const walk = (n: any): void => {
    if (n.JoinExpr) return (walk(n.JoinExpr.larg), walk(n.JoinExpr.rarg));
    const v = n.RangeVar;
    if (v) rels.set(v.alias?.aliasname ?? v.relname, v.mantle === "table" ? schemas[String(v.relname).toLowerCase()] : undefined);
    else rels.set((n.RangeSubselect ?? n.RangeFunction)?.alias?.aliasname ?? "", undefined);
  };
  for (const f of sel.fromClause ?? []) walk(f);
  const keys: string[] = [];
  for (const { ResTarget: r } of sel.targetList) {
    const fields = r.val?.ColumnRef?.fields;
    if (!r.name && fields?.at(-1)?.A_Star) {
      const from = fields.length > 1 ? [rels.get(fields[0].String.sval)] : [...rels.values()];
      if (from.some((s) => !s)) return undefined;
      for (const s of from) keys.push(...starCols(s!));
      continue;
    }
    const name: string | undefined = r.name ?? fields?.at(-1)?.String?.sval;
    if (!name) return undefined;
    keys.push(name);
  }
  return [...new Set(keys)];
}

/** `values` of an insert: what the Schema requires, defaults optional, and never the scope field, which Store fills. */
function insertValues(s: PlanSchema): string {
  const props = Object.keys(s.schema.properties ?? {}).filter((p) => p.toLowerCase() !== s.scope);
  const defaults = props.filter((p) => Object.hasOwn(s.schema.properties![p]!, "default"));
  const rest = props.filter((p) => !defaults.includes(p));
  const pick = (ks: string[]) => `Pick<Schemas[${key(s.name)}], ${ks.map(key).join(" | ")}>`;
  const value = [...(rest.length ? [pick(rest)] : []), ...(defaults.length ? [`Partial<${pick(defaults)}>`] : [])].join(" & ") || "{}";
  return `  readonly ${key(s.name)}: ${value};`;
}

export function emitMantleModule(plan: RuntimePlan, linked: LinkedManifestSet): string {
  const schemas = Object.values(plan.schemas).sort((a, b) => byName(a.name, b.name));
  const views = Object.entries(plan.views).sort(([a], [b]) => byName(a, b));
  const rows = Object.fromEntries(views.flatMap(([name, v]) => {
    const keys = viewRowKeys(v, plan.schemas);
    return keys ? [[name, `{ ${keys.map((k) => `readonly ${key(k)}: unknown;`).join(" ")} }`]] : [];
  }));
  const types = emitTypesFromManifests({
    schemas: linked.schemas.map((x) => x.manifest), procedures: linked.procedures.map((x) => x.manifest), views: linked.views.map((x) => x.manifest), namespace: NS, rows,
  }).source.replace(/^\/\/ .*\n\n/, "").trimEnd();
  const refs = new Map<string, string[]>();
  for (const [name, p] of Object.entries(plan.procedures)) if ("ref" in p.handler) refs.set(p.handler.ref, [...(refs.get(p.handler.ref) ?? []), manifestTypeIdentifier(name)]);

  return [
    "// Generated by `mantle generate`. Do not edit by hand.",
    'import type { Caller, HandlerContext, InvocationCause, MantleStore, StoreDelete, StoreInsert, StoreRow, StoreSelect, StoreSelectResult, StoreUpdate, StoreWriteResult } from "@aotter/mantle";',
    'import type { RuntimePlan } from "@aotter/mantle/spec";',
    'import planFile from "./plan.json" with { type: "json" };',
    "",
    "/** The sealed plan, for `createMantle(service, { plan })`. */",
    "export const plan = planFile.plan as unknown as RuntimePlan;",
    "/** SHA-256 of the manifest sources the plan was compiled from; not part of the fingerprint. */",
    "export const sourceHash: string = planFile.sourceHash;",
    "",
    types,
    "",
    "export interface Schemas {",
    ...schemas.map((s) => `  readonly ${key(s.name)}: ${NS}.Entry_${manifestTypeIdentifier(s.name)};`),
    "}",
    "type InsertValues = {",
    ...schemas.map(insertValues),
    "};",
    "",
    "export interface Views {",
    ...views.map(([name, v]) => {
      const id = manifestTypeIdentifier(name);
      return `  readonly ${key(name)}: { readonly input: ${v.input ? `${NS}.ViewInput_${id}` : "undefined"}; readonly row: ${NS}.ViewRow_${id}; readonly required: ${(v.input?.required?.length ?? 0) > 0} };`;
    }),
    "}",
    "",
    "/** Views page with `limit` and `cursor` only (ADR-0032 decision 5). */",
    "export type ViewOptions<N extends keyof Views> = { readonly limit?: number; readonly cursor?: string } &",
    '  (Views[N]["input"] extends undefined ? {} : Views[N]["required"] extends true ? { readonly input: Views[N]["input"] } : { readonly input?: Views[N]["input"] });',
    "type Write = { [N in keyof Schemas & string]:",
    '  | (Omit<StoreInsert, "insert" | "values"> & { readonly insert: N; readonly values: InsertValues[N] })',
    '  | (Omit<StoreUpdate, "update" | "set"> & { readonly update: N; readonly set: Partial<InsertValues[N]> })',
    '  | (Omit<StoreDelete, "delete"> & { readonly delete: N })',
    "}[keyof Schemas & string];",
    "",
    "/** `runtime.store`, typed over this plan's Schemas and Views. */",
    'export type Store = Omit<MantleStore, "as" | "select" | "write" | "view"> & {',
    "  as(caller: Caller, cause?: InvocationCause): CallerStore;",
    // one overload per Schema, not a generic: Core's untyped `ctx.store` must stay assignable to this one
    ...schemas.map((s) => `  select(query: Omit<StoreSelect, "from"> & { readonly from: ${key(s.name)} }): Promise<StoreSelectResult<StoreRow & Partial<Schemas[${key(s.name)}]>>>;`),
    "  write(ops: readonly Write[]): Promise<readonly StoreWriteResult[]>;",
    '  view<N extends keyof Views & string>(name: N, ...options: Views[N]["required"] extends true ? [ViewOptions<N>] : [ViewOptions<N>?]): Promise<StoreSelectResult<Views[N]["row"]>>;',
    "};",
    "/** `ctx.store`: scope follows the caller. */",
    'export type CallerStore = Omit<Store, "as" | "sweepExpired">;',
    "",
    "/** A handler receives this plan's typed `ctx.store`. */",
    'export type Handler<I, O, Env = unknown> = (input: I, ctx: Omit<HandlerContext<Env>, "store"> & { readonly store: CallerStore }) => O | Promise<O>;',
    "/** Exactly the plan's handler refs: a missing or an extra one is a type error. */",
    // `{}` would accept any object, so a plan without refs takes none
    ...(refs.size ? [
      "export type MantleHandlers<Env = unknown> = {",
      ...[...refs].sort(([a], [b]) => byName(a, b)).map(([ref, names]) => {
        const ns = names.sort(byName);
        return `  readonly ${key(ref)}: Handler<${ns.map((n) => `${NS}.ProcInput_${n}`).join(" | ")}, ${ns.map((n) => `${NS}.ProcOutput_${n}`).join(" | ")}, Env>;`;
      }),
      "};",
    ] : ["export type MantleHandlers<Env = unknown> = Readonly<Record<string, never>>;"]),
    "",
  ].join("\n");
}
