/**
 * `.mantle/generated/mantle.ts` (ADR-0032 amendment "mantle generate"): the plan from `plan.json`, the manifest types (`emitTypesFromManifests`)
 * namespace, and a typed Store and `MantleHandlers` over exactly this plan. Types only, apart from the `plan` import.
 */
import { emitTypesFromManifests, manifestTypeIdentifier, viewOutputs, type LinkedManifestSet, type PlanSchema, type PlanView, type RuntimePlan } from "../spec/index.js";

const NS = "Mantle";
const byName = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);
const key = (s: string) => JSON.stringify(s);

/**
 * A View row, read off the compiled SELECT (`viewOutputs`): an output that is a Schema field read unchanged comes back decoded
 * and under the declared name, so it takes that field's type; any other output is `unknown`. Undefined (the row stays
 * `unknown`) when an output has no name, or a `*` reads a subquery or `json_each`.
 */
function viewRow(view: PlanView, schemas: RuntimePlan["schemas"]): string | undefined {
  const { keys, columns } = viewOutputs(view, schemas);
  if (!keys) return undefined;
  const fields = keys.map((k) => {
    const c = Object.hasOwn(columns, k) ? columns[k] : undefined;
    const s = c && schemas[c.schema]!;
    const declared = s ? s.names[c.field] ?? c.field : undefined;
    return s ? `readonly ${key(k === c.field ? declared! : k)}: NonNullable<Entry_${manifestTypeIdentifier(s.name)}[${key(declared!)}]> | null;` : `readonly ${key(k)}: unknown;`;
  });
  return `{ ${fields.join(" ")} }`;
}

/**
 * `values` of an insert: what the Schema requires, defaults optional, and never the scope field, which Store fills. An insert
 * into a publishing Schema is a draft, so everything is optional there.
 */
function insertValues(s: PlanSchema): string {
  const props = Object.keys(s.schema.properties ?? {}).filter((p) => p.toLowerCase() !== s.scope);
  const optional = s.publishing ? props : props.filter((p) => Object.hasOwn(s.schema.properties![p]!, "default"));
  const rest = props.filter((p) => !optional.includes(p));
  const pick = (ks: string[]) => `Pick<Schemas[${key(s.name)}], ${ks.map(key).join(" | ")}>`;
  const value = [...(rest.length ? [pick(rest)] : []), ...(optional.length ? [`Partial<${pick(optional)}>`] : [])].join(" & ") || "{}";
  return `  readonly ${key(s.name)}: ${value};`;
}

/** An update sets values, or on a publishing Schema moves the status alone. */
const updateSet = (s: PlanSchema) => `  readonly ${key(s.name)}: Partial<InsertValues[${key(s.name)}]>${s.publishing ? " | { readonly status: ContentState }" : ""};`;

export function emitMantleModule(plan: RuntimePlan, linked: LinkedManifestSet): string {
  const schemas = Object.values(plan.schemas).sort((a, b) => byName(a.name, b.name));
  const views = Object.entries(plan.views).sort(([a], [b]) => byName(a, b));
  const rows = Object.fromEntries(views.flatMap(([name, v]) => {
    const row = viewRow(v, plan.schemas);
    return row ? [[name, row]] : [];
  }));
  const types = emitTypesFromManifests({
    schemas: linked.schemas.map((x) => x.manifest), procedures: linked.procedures.map((x) => x.manifest), views: linked.views.map((x) => x.manifest), namespace: NS, rows,
  }).source.replace(/^\/\/ .*\n\n/, "").trimEnd();
  const refs = new Map<string, string[]>();
  for (const [name, p] of Object.entries(plan.procedures)) if ("ref" in p.handler) refs.set(p.handler.ref, [...(refs.get(p.handler.ref) ?? []), manifestTypeIdentifier(name)]);

  return [
    "// Generated by `mantle generate`. Do not edit by hand.",
    'import type { Caller, HandlerContext, InvocationCause, MantleStore, StoreDelete, StoreInsert, StoreRow, StoreSelect, StoreSelectResult, StoreUpdate, StoreWriteResult } from "@aotter/mantle";',
    'import type { ContentState, RuntimePlan } from "@aotter/mantle/spec";',
    'import planFile from "./plan.json" with { type: "json" };',
    "",
    "/** The sealed plan, for `createMantle(service, { plan })`. */",
    "export const plan = planFile.plan as unknown as RuntimePlan;",
    "/** SHA-256 of the manifest sources the plan was compiled from; not part of the fingerprint. */",
    "export const sourceHash: string = planFile.sourceHash;",
    "",
    types,
    "",
    "export interface Schemas {",
    ...schemas.map((s) => `  readonly ${key(s.name)}: ${NS}.Entry_${manifestTypeIdentifier(s.name)};`),
    "}",
    "type InsertValues = {",
    ...schemas.map(insertValues),
    "};",
    "type UpdateSet = {",
    ...schemas.map(updateSet),
    "};",
    "",
    "export interface Views {",
    ...views.map(([name, v]) => {
      const id = manifestTypeIdentifier(name);
      return `  readonly ${key(name)}: { readonly input: ${v.input ? `${NS}.ViewInput_${id}` : "undefined"}; readonly row: ${NS}.ViewRow_${id}; readonly required: ${(v.input?.required?.length ?? 0) > 0} };`;
    }),
    "}",
    "",
    "/** Views page with `limit` and `cursor` only (ADR-0032 decision 5). */",
    "export type ViewOptions<N extends keyof Views> = { readonly limit?: number; readonly cursor?: string } &",
    '  (Views[N]["input"] extends undefined ? {} : Views[N]["required"] extends true ? { readonly input: Views[N]["input"] } : { readonly input?: Views[N]["input"] });',
    "type Write = { [N in keyof Schemas & string]:",
    '  | (Omit<StoreInsert, "insert" | "values"> & { readonly insert: N; readonly values: InsertValues[N] })',
    '  | (Omit<StoreUpdate, "update" | "set"> & { readonly update: N; readonly set: UpdateSet[N] })',
    '  | (Omit<StoreDelete, "delete"> & { readonly delete: N })',
    "}[keyof Schemas & string];",
    "",
    "/** `runtime.store`, typed over this plan's Schemas and Views. */",
    'export type Store = Omit<MantleStore, "as" | "select" | "write" | "view"> & {',
    "  as(caller: Caller, cause?: InvocationCause): CallerStore;",
    // one overload per Schema, not a generic: Core's untyped `ctx.store` must stay assignable to this one
    ...schemas.map((s) => `  select(query: Omit<StoreSelect, "from"> & { readonly from: ${key(s.name)} }): Promise<StoreSelectResult<StoreRow & Partial<Schemas[${key(s.name)}]>>>;`),
    "  write(ops: readonly Write[]): Promise<readonly StoreWriteResult[]>;",
    '  view<N extends keyof Views & string>(name: N, ...options: Views[N]["required"] extends true ? [ViewOptions<N>] : [ViewOptions<N>?]): Promise<StoreSelectResult<Views[N]["row"]>>;',
    "};",
    "/** `ctx.store`: scope follows the caller. */",
    'export type CallerStore = Omit<Store, "as" | "sweepExpired">;',
    "",
    "/** A handler receives this plan's typed `ctx.store`. */",
    'export type Handler<I, O, Env = unknown> = (input: I, ctx: Omit<HandlerContext<Env>, "store"> & { readonly store: CallerStore }) => O | Promise<O>;',
    "/** Exactly the plan's handler refs: a missing or an extra one is a type error. */",
    // `{}` would accept any object, so a plan without refs takes none
    ...(refs.size ? [
      "export type MantleHandlers<Env = unknown> = {",
      ...[...refs].sort(([a], [b]) => byName(a, b)).map(([ref, names]) => {
        const ns = names.sort(byName);
        return `  readonly ${key(ref)}: Handler<${ns.map((n) => `${NS}.ProcInput_${n}`).join(" | ")}, ${ns.map((n) => `${NS}.ProcOutput_${n}`).join(" | ")}, Env>;`;
      }),
      "};",
    ] : ["export type MantleHandlers<Env = unknown> = Readonly<Record<string, never>>;"]),
    "",
  ].join("\n");
}
