import {
  mkdir,
  readFile,
  stat,
  writeFile,
} from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { cwd } from "node:process";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import {
  EmitTypesUseCase,
  ValidateManifestsUseCase,
  type Manifest,
  type ProcedureManifest,
} from "@aotter/mantle-spec";
import { loadManifestsFromRoot } from "@aotter/mantle-spec/cli";

const PROJECTED_SKILLS = ["develop", "plugin", "theme", "update"] as const;

export interface GenerateOptions {
  readonly manifests: string;
  readonly output: string;
  readonly namespace: string;
  readonly check: boolean;
  readonly skills: boolean;
}

export async function runGenerate(rawArgs: readonly string[]): Promise<number> {
  let options: GenerateOptions;
  try {
    const parsed = parseGenerateArgs(rawArgs);
    if (parsed === null) {
      printGenerateHelp();
      return 0;
    }
    options = parsed;
  } catch (error) {
    process.stderr.write(`${message(error)}\n`);
    return 2;
  }

  const loaded = await loadManifestsFromRoot(options.manifests);
  const validation = ValidateManifestsUseCase.run({
    manifests: loaded.manifests,
    filePaths: loaded.filePaths,
  });
  const errors = [...loaded.parseErrors, ...validation.diagnostics]
    .filter((diagnostic) => diagnostic.severity === "error");
  if (errors.length) {
    for (const error of errors) {
      process.stderr.write(`${error.code} ${error.path}: ${error.message}\n`);
    }
    return 1;
  }

  const output = resolve(cwd(), options.output);
  const files = new Map<string, string>([
    [join(output, "site.ts"), emitManifestModule(loaded.manifests, options.namespace)],
    [join(output, "types.d.ts"), emitConsumerTypes(loaded.manifests, options.namespace)],
  ]);
  let stale = false;
  for (const [path, source] of files) {
    stale = !(await syncText(path, source, options.check)) || stale;
  }
  if (options.skills) {
    const source = await skillSourceRoot();
    for (const skill of PROJECTED_SKILLS) {
      for (const tool of [".agent", ".claude"]) {
        const destination = resolve(cwd(), tool, "skills", `mantle-${skill}`, "SKILL.md");
        stale = !(await syncText(
          destination,
          await readFile(join(source, skill, "SKILL.md"), "utf8"),
          options.check,
        )) || stale;
      }
    }
  }
  if (stale && options.check) {
    process.stderr.write("Mantle generated files are stale; run `mantle generate`.\n");
    return 1;
  }
  return 0;
}

function parseGenerateArgs(rawArgs: readonly string[]): GenerateOptions | null {
  const { values } = parseArgs({
    args: [...rawArgs],
    allowNegative: true,
    options: {
      manifests: { type: "string" },
      output: { type: "string", short: "o" },
      namespace: { type: "string" },
      check: { type: "boolean" },
      skills: { type: "boolean", default: true },
      help: { type: "boolean", short: "h" },
    },
  });
  if (values.help) return null;
  return {
    manifests: values.manifests ?? "./manifests",
    output: values.output ?? ".mantle/generated",
    namespace: values.namespace ?? "MantleSite",
    check: values.check === true,
    skills: values.skills !== false,
  };
}

function printGenerateHelp(): void {
  process.stdout.write(`mantle generate — compile manifests and project Core skills

Usage: mantle generate [options]

Options:
  --manifests <dir>   Manifest root (default: ./manifests)
  -o, --output <dir>  Generated module root (default: .mantle/generated)
  --namespace <name>  Generated type namespace (default: MantleSite)
  --check             Fail instead of writing when output is stale
  --no-skills         Skip .agent/.claude Core skill projections
  -h, --help          This help
`);
}

function emitManifestModule(manifests: readonly Manifest[], namespace: string): string {
  const views = manifests.flatMap((manifest, index) =>
    manifest.kind === "View" ? [{ manifest, index }] : []
  );
  const source = [
    "// Generated by `mantle generate`. Do not edit by hand.",
    'import type { Manifest } from "@aotter/mantle/spec";',
    ...(views.length
      ? [
          'import type { CmsRuntime, ExecuteViewRequest, ExecuteViewResponse } from "@aotter/mantle/runtime";',
          `import type { ${namespace} } from "./types.js";`,
        ]
      : []),
    "",
    `export const manifest = ${JSON.stringify(manifests, null, 2)} as const satisfies readonly Manifest[];`,
    "",
  ];
  if (!views.length) return source.join("\n");

  source.push(
    'type ViewRequest = Omit<ExecuteViewRequest, "view">;',
    "",
    "export interface MantleSiteRuntime {",
    "  readonly views: {",
    ...views.map(({ manifest }) => {
      const name = tsId(manifest.metadata.name);
      return `    readonly ${JSON.stringify(manifest.metadata.name)}: (request?: ViewRequest) => Promise<ExecuteViewResponse<${namespace}.ViewRow_${name}>>;`;
    }),
    "  };",
    "}",
    "",
    "export function bindMantleSite(runtime: CmsRuntime): MantleSiteRuntime {",
    "  return {",
    "    views: {",
    ...views.map(({ manifest, index }) => {
      const name = tsId(manifest.metadata.name);
      return `      ${JSON.stringify(manifest.metadata.name)}: (request = {}) => runtime.executeView.execute<${namespace}.ViewRow_${name}>({ ...request, view: manifest[${index}] }),`;
    }),
    "    },",
    "  };",
    "}",
    "",
  );
  return source.join("\n");
}

function emitConsumerTypes(manifests: readonly Manifest[], namespace: string): string {
  const generated = EmitTypesUseCase.run({ manifests, namespace }).source
    .replace("Generated by `mantle emit-types`", "Generated by `mantle generate`");
  const procedures = manifests.filter(
    (manifest): manifest is ProcedureManifest =>
      manifest.kind === "Procedure" && manifest.spec.handler.kind === "ref",
  );
  if (!procedures.length) return generated;
  const handlers = new Map<string, { inputs: Set<string>; outputs: Set<string> }>();
  for (const procedure of procedures) {
    const name = tsId(procedure.metadata.name);
    const ref = procedure.spec.handler.kind === "ref" ? procedure.spec.handler.ref : "";
    const types = handlers.get(ref) ?? { inputs: new Set<string>(), outputs: new Set<string>() };
    types.inputs.add(`${namespace}.ProcInput_${name}`);
    types.outputs.add(`${namespace}.ProcOutput_${name}`);
    handlers.set(ref, types);
  }
  return [
    'import type { HandlerFn } from "@aotter/mantle/runtime";',
    "",
    generated.trimEnd(),
    "",
    "export type MantleHandlers<Env = unknown> = {",
    ...[...handlers].map(([ref, types]) =>
      `  readonly ${JSON.stringify(ref)}: HandlerFn<${[...types.inputs].join(" | ")}, ${[...types.outputs].join(" | ")}, Env>;`
    ),
    "}",
    "",
  ].join("\n");
}

function tsId(name: string): string {
  return name.replace(/[^a-zA-Z0-9_$]+/g, "_");
}

async function syncText(path: string, expected: string, check: boolean): Promise<boolean> {
  const current = await readFile(path, "utf8").catch(() => null);
  if (current === expected) return true;
  if (check) return false;
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, expected, "utf8");
  return true;
}

async function skillSourceRoot(): Promise<string> {
  const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  for (const candidate of [join(packageRoot, "skills"), resolve(packageRoot, "../../skills")]) {
    if ((await stat(candidate).catch(() => null))?.isDirectory()) return candidate;
  }
  throw new Error("Mantle Core skills are missing from the installed package.");
}

function message(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
