import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { cwd, stderr, stdout } from "node:process";
import { parseArgs } from "node:util";
import {
  EmitTypesUseCase,
  ValidateManifestsUseCase,
  type Manifest,
  type ProcedureManifest,
} from "@aotter/mantle-spec";
import { loadManifestsFromRoot } from "@aotter/mantle-spec/cli";

interface GenerateOptions {
  readonly manifests: string;
  readonly output: string;
  readonly namespace: string;
  readonly check: boolean;
}

export async function runGenerate(rawArgs: readonly string[]): Promise<number> {
  let options: GenerateOptions;
  try {
    const parsed = parseGenerateArgs(rawArgs);
    if (parsed === null) {
      printHelp();
      return 0;
    }
    options = parsed;
  } catch (error) {
    stderr.write(`${message(error)}\n`);
    return 2;
  }

  const loaded = await loadManifestsFromRoot(options.manifests);
  const validation = ValidateManifestsUseCase.run({
    manifests: loaded.manifests,
    filePaths: loaded.filePaths,
  });
  const errors = [...loaded.parseErrors, ...validation.diagnostics]
    .filter((diagnostic) => diagnostic.severity === "error");
  if (errors.length > 0) {
    for (const error of errors) {
      stderr.write(`${error.code} ${error.path}: ${error.message}\n`);
    }
    return 1;
  }

  const output = resolve(cwd(), options.output);
  const files = new Map([
    [join(output, "site.ts"), emitManifestModule(loaded.manifests)],
    [join(output, "types.d.ts"), emitTypes(loaded.manifests, options.namespace)],
  ]);
  let stale = false;
  for (const [path, source] of files) {
    stale = !(await syncText(path, source, options.check)) || stale;
  }
  if (stale && options.check) {
    stderr.write("Mantle generated files are stale; run `mantle generate`.\n");
    return 1;
  }
  return 0;
}

function parseGenerateArgs(rawArgs: readonly string[]): GenerateOptions | null {
  const { values } = parseArgs({
    args: [...rawArgs],
    options: {
      manifests: { type: "string" },
      output: { type: "string", short: "o" },
      namespace: { type: "string" },
      check: { type: "boolean" },
      help: { type: "boolean", short: "h" },
    },
  });
  if (values.help) return null;
  const namespace = values.namespace ?? "MantleSite";
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(namespace)) {
    throw new Error(`--namespace must be a TypeScript identifier; got ${JSON.stringify(namespace)}`);
  }
  return {
    manifests: values.manifests ?? "./manifests",
    output: values.output ?? ".mantle/generated",
    namespace,
    check: values.check === true,
  };
}

function printHelp(): void {
  stdout.write(`mantle generate — compile manifests and handler types

Usage: mantle generate [options]

Options:
  --manifests <dir>   Manifest root (default: ./manifests)
  -o, --output <dir>  Generated root (default: .mantle/generated)
  --namespace <name>  Generated type namespace (default: MantleSite)
  --check             Fail without writing when output is stale
  -h, --help          This help
`);
}

function emitManifestModule(manifests: readonly Manifest[]): string {
  return [
    "// Generated by `mantle generate`. Do not edit by hand.",
    'import type { Manifest } from "@aotter/mantle/spec";',
    "",
    `export const manifest = ${JSON.stringify(manifests, null, 2)} as const satisfies readonly Manifest[];`,
    "",
  ].join("\n");
}

function emitTypes(manifests: readonly Manifest[], namespace: string): string {
  const generated = EmitTypesUseCase.run({ manifests, namespace }).source
    .replace("Generated by `mantle emit-types`", "Generated by `mantle generate`");
  const procedures = manifests.filter(
    (manifest): manifest is ProcedureManifest =>
      manifest.kind === "Procedure" && manifest.spec.handler.kind === "ref",
  );
  if (procedures.length === 0) return generated;

  const handlers = new Map<string, { inputs: string[]; outputs: string[] }>();
  for (const procedure of procedures) {
    const name = tsId(procedure.metadata.name);
    const ref = procedure.spec.handler.kind === "ref" ? procedure.spec.handler.ref : "";
    const types = handlers.get(ref) ?? { inputs: [], outputs: [] };
    types.inputs.push(`${namespace}.ProcInput_${name}`);
    types.outputs.push(`${namespace}.ProcOutput_${name}`);
    handlers.set(ref, types);
  }
  return [
    'import type { HandlerFn } from "@aotter/mantle/runtime";',
    "",
    generated.trimEnd(),
    "",
    "export type MantleHandlers<Env = unknown> = {",
    ...[...handlers].map(([ref, types]) =>
      `  readonly ${JSON.stringify(ref)}: HandlerFn<${types.inputs.join(" | ")}, ${types.outputs.join(" | ")}, Env>;`
    ),
    "};",
    "",
  ].join("\n");
}

function tsId(name: string): string {
  return name.replace(/[^a-zA-Z0-9_$]+/g, "_");
}

async function syncText(path: string, expected: string, check: boolean): Promise<boolean> {
  const current = await readFile(path, "utf8").catch(() => null);
  if (current === expected) return true;
  if (check) return false;
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, expected, "utf8");
  return true;
}

function message(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
