// Commentary that goes into REPORT.txt. It is written by hand; the checks it cites are in the evidence
// section and fail the run if they stop holding. Numbered by the ADR decision they amend.
// Numbers a case measures or chooses live in `facts` (the case sets them), so the text cannot drift from the run.
export const facts = { trees: 40, dstMin: 0, dstMax: 0, caught: 0, positions: 0 };

export const findings = () => [
  'Decision 3 (printer). Four printer overrides, not three: ParamRef, TypeCast, A_Const, and A_Expr (x LIKE p ESCAPE e parses to',
  '  LIKE with pg_catalog.like_escape(p, e); SQLite has only the ESCAPE clause). Four more places rewrite the AST because SQLite lacks the',
  '  PostgreSQL construct (function prefix and SQL-syntax calls, btrim -> trim, = ANY (subquery) -> IN, type names). 4 + 4 is under the',
  '  ADR threshold of "about a dozen": Kysely is not needed. [1c, 1g]',
  'Decision 3 (printer). `$n` is not a syntax error on D1: SQLite reads it as a named parameter numbered by first appearance, so binds',
  '  shift silently when ?3 appears before ?2. Only the corpus item insert-select-input catches it. The ADR should say the ParamRef',
  '  override is a correctness fix, not cosmetics. [1c]',
  `Decision 3 (printer). Operator precedence needs no override: pgsql-deparser parenthesizes nested operators, and ${facts.trees} random`,
  '  integer/boolean trees plus the `||` cases evaluate on D1 to the tree\'s value; the same SQL without its parentheses does not. [1f]',
  'Decision 2 (identifiers). The keywords SQLite rejects unquoted while the printer leaves them bare are, measured against all 147:',
  '  add alter autoincrement commit delete drop escape index insert nothing raise set transaction update. `match` and `glob`, named in',
  '  the ADR, are fine. The list is a measurement of pgsql-deparser 18.3.8 and D1\'s SQLite: 1d fails if either changes it. [1d]',
  'Decision 2 (windows). "The compiler appends id to the window\'s ORDER BY" is wrong for anything but row_number(): the appended key makes',
  '  peers distinct, so rank() stops tying and a running sum stops including its peers (PostgreSQL semantics). Append only for',
  '  row_number(). [1 corpus: window-ties]',
  'Decision 2 (writes). The requisition example in the prototype and the Whiteboard names `id` in INSERT INTO orders on a scoped Schema. Decision',
  '  8 says a scoped Schema generates its own ids, and this is refused (SQL_WRITE). The example must not name id. [Case 5]',
  'Decision 4 (classification). One row of VALUES with ON CONFLICT must be a set op, or a DO NOTHING that hits the conflict fails with CONFLICT.',
  '  State it in the classification rule ("ON CONFLICT is a set op" appears under Writes, not under Classification). [1 corpus: upsert-nothing]',
  'Decision 4 (hooks). RETURNING * and most column lists carry neither id nor version, but an after hook needs both: the compiler adds hidden',
  '  _mantle_id and _mantle_version columns for a hooked target and the executor splits them off. State that ctx.cause.rows always carry',
  '  id and version. [Case 1]',
  'Decision 4 (before hooks). A row op whose row is not visible must fail with CONFLICT without calling the hook, or the hook can probe for',
  '  another owner\'s row. [Case 4]',
  'Decision 4 (counting). D1\'s meta.changes counts trigger writes (5 for a one-row UPDATE on a searchable row), so changes() inside the',
  '  batch is required, as the ADR says. RAISE(IGNORE) in a BEFORE INSERT trigger on _mantle_assert keeps no rows. [Case 8, D1 facts]',
  'Decision 5 (types). `? / 2`, exact sums over numeric(12,2), microsecond comparisons and date_trunc across daylight saving all give',
  '  PostgreSQL\'s results. numeric input beyond its scale is refused, not rounded. CAST(x AS int) truncates where PostgreSQL rounds',
  '  (2.7 gives 2; -2.7 gives -2; \'12.5\' gives 12): the warning is SQL_CAST_TRUNC. CAST(x AS bool) is lowered to x <> 0. A CAST of a',
  '  non-literal to timestamptz, date or numeric is refused: it would need the arithmetic rewrite the ADR defers. [Case 6]',
  'Decision 5 (time zone). Transitions generated with Intl (261 rows for New York 1970-2100, three-day scan plus bisection) match the Intl oracle',
  `  on ${facts.dstMin} to ${facts.dstMax} instants per zone (New York, Berlin, Lord Howe, Kolkata, Apia, Taipei), including every half hour within 6 h of each`,
  '  transition and the day Apia skipped. Inside a repeated whole hour each pass truncates to its own hour start (05:30Z gives 05:00Z, 06:30Z',
  '  gives 06:00Z); whether PostgreSQL picks the same was not verified (no PostgreSQL here), so the ADR should not claim parity for the',
  '  repeated hour or for Lord Howe\'s half-hour gap. [Case 6]',
  'Decision 8 (positions). The AST does not say which keys hold a relation, so the "IR position union" is a hand-kept list. It is bound to',
  '  @pgsql/types (each edge is Edge<Node, KeyOf<Node>>, so a renamed key fails tsc), ALL_EDGES_REACHED fails when an edge has no position,',
  '  the probe list is Record<RelationPosition, Probe> `satisfies`, and the policy pass throws on a relation reached through an edge it has',
  '  no name for (fail closed). All three tsc failures are shown by scratch copies. Switching the visibility predicate off is caught by',
  `  ${facts.caught} of ${facts.positions} probes; insert-target is protected by the scope/id fill and the scope-including unique index instead. [Case 7, Typecheck]`,
  'Decision 8 (search and near). search() and near() need the wrapper to expose rowid as _rid; search_rank(t) needs the query of the sibling',
  '  search(t, q); PostgreSQL\'s grammar has no MATCH, so the printed form is `fts = q` (FTS5 accepts it, results identical to MATCH).',
  '  near() takes a literal radius and input-or-literal coordinates, because the bounding box is bound from the input at run time. [Case 8]',
  'Decision 9 (D1). R*Tree is refused by workerd 1.20260730 (only fts5 and fts5vocab virtual tables are authorized) and allowed by',
  '  1.20260903.1, the version the monorepo pins. Production D1 must be checked: production-probe.sql. [D1 facts]',
  'Decision 3 (diagnostics, ADR-0034 How to apply 3). Proposed codes: SQL_SYNTAX SQL_UNSUPPORTED SQL_FUNCTION SQL_RELATION SQL_COLUMN SQL_WRITE',
  '  SQL_SHAPE SQL_TYPE, and the warning SQL_CAST_TRUNC. libpg-query gives no location for clause keys (WITH, OFFSET, RIGHT, UNION, FOR UPDATE ...),',
  '  so the CLI finds the keyword in the source; the remaining refusals without a position are whole-statement ones. [Case 5]',
  'Decision 1 (grammar version). libpg-query 18.1.5 reports 180004, the value the plan records; the runtime refuses another. [Case 5]',
];

export const NOT_COVERED = [
  'Production D1 (only local; see production-probe.sql). Sequences and nextval(). Foreign-key RESTRICT triggers and the same-owner rule. The',
  'rule "a selected column must be grouped or aggregated" and the NULL-position rule for a nullable sort key. `ctx.store.select` / `write`',
  'JSON-to-AST converter and handler-built IR. Cursors over distance(), and cursors over nullable keys. A View that pages a window or a set',
  'op. Hooks over a scoped Schema\'s upserts. The Cloud plan upload (host protocol 3) and Control\'s JS validation of the IR. Admin\'s',
  'searchFields. Storage convergence for an existing table (every case starts from an empty D1). Hour truncation in Lord Howe (a',
  'half-hour gap); a zone whose day starts in a gap. The runtime runs in Node and reaches D1 through the Worker in src/worker.mjs; the compiler and',
  'policy pass are not bundled into a Worker here.',
];
