// @ts-nocheck test code over loosely typed plans and rows
/**
 * ADR-0044's cold-start contract: a fresh runtime's first call of a lowered View or inline Procedure performs no dialect check,
 * no applyPolicy and no print; a plan without lowered statements still does, once.
 */
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";

vi.mock("../../src/d1/print.js", async (importOriginal) => { const m = await importOriginal<typeof import("../../src/d1/print.js")>(); return { ...m, print: vi.fn(m.print) }; });
vi.mock("../../src/core/sql/policy.js", async (importOriginal) => { const m = await importOriginal<typeof import("../../src/core/sql/policy.js")>(); return { ...m, applyPolicy: vi.fn(m.applyPolicy) }; });

import { LocalD1 } from "../../src/cloudflare/testing/d1.js";
import { createMantleRuntime } from "../../src/core/index.js";
import { withLowering } from "../../src/core/sql/lowered.js";
import { print } from "../../src/d1/print.js";
import { applyPolicy } from "../../src/core/sql/policy.js";
import { d1Dialect } from "../../src/d1/dialect.js";
import { sqliteStorage } from "../../src/d1/index.js";
import { MANIFESTS, anonymous, compile, deterministic, handlers, reseal, user } from "./lowered-fixture.js";

let lowered, stripped, d1a, d1b;
beforeAll(async () => {
  const plan = await compile();
  ({ plan: lowered } = await withLowering(plan, d1Dialect));
  stripped = await reseal(lowered, (p) => { delete p.lowered; return p; });
  [d1a, d1b] = await Promise.all([LocalD1.create(), LocalD1.create()]);
}, 60_000);
afterAll(() => Promise.all([d1a?.dispose(), d1b?.dispose()]));

/** A runtime on its own database, its dialect's check counted. */
async function boot(plan, d1) {
  const storage = sqliteStorage(d1);
  const check = vi.fn(storage.dialect.check);
  const counted = { ...storage, dialect: { ...storage.dialect, check } };
  const runtime = await createMantleRuntime({ plan, handlers, storage: counted, schedules: true, ...deterministic() });
  return { runtime, check };
}
const counters = (check) => ({ check: check.mock.calls.length, applyPolicy: vi.mocked(applyPolicy).mock.calls.length, print: vi.mocked(print).mock.calls.length });
const reset = (check) => { check.mockClear(); vi.mocked(applyPolicy).mockClear(); vi.mocked(print).mockClear(); };

/** The calls whose first execution is measured: Views by mode, and both inline Procedures (the insert fires an after hook, so its statements carry the hook's RETURNING). */
const CALLS = [
  ["add-item", (r) => r.invokeProcedure({ procedure: "add-item", input: { name: "apple", stock: 5 }, caller: user("o1"), cause: { kind: "http", id: "c1" } })],
  ["add-item again", (r) => r.invokeProcedure({ procedure: "add-item", input: { name: "berry", stock: 2 }, caller: user("o1"), cause: { kind: "http", id: "c2" } })],
  ["public View", (r) => r.store.as(anonymous).view("shelf")],
  ["public View, next page", async (r) => { const first = await r.store.as(anonymous).view("shelf", { limit: 1 }); return r.store.as(anonymous).view("shelf", { limit: 1, cursor: first.nextCursor }); }],
  ["staff View with input", (r) => r.store.as(user("o1")).view("low-stock", { input: { max: 10 } })],
  ["staff View, host (trusted)", (r) => r.store.view("low-stock", { limit: 12 })],
  ["View without ORDER BY", (r) => r.store.as(user("o1")).view("everything")],
];

describe("a fresh runtime on a plan with lowered statements", () => {
  it("makes no dialect check, no applyPolicy and no print on the first call of any lowered View or inline Procedure", async () => {
    const { runtime, check } = await boot(lowered, d1a);
    expect(runtime.bootReport().lowered).toBe("used");
    const seeded = [];
    for (const [name, call] of CALLS) {
      reset(check);
      await call(runtime);
      seeded.push([name, counters(check)]);
    }
    // the add-item runs first: its insert and the hook are lowered too
    expect(seeded).toEqual(CALLS.map(([name]) => [name, { check: 0, applyPolicy: 0, print: 0 }]));
    // the page size is a bind: a size nobody enumerated is no different, nor is the last page
    reset(check);
    for (const limit of [1, 2, 3, 7, 500]) await runtime.store.as(anonymous).view("shelf", { limit });
    expect(counters(check)).toEqual({ check: 0, applyPolicy: 0, print: 0 });
  });

  it("returns the rows a runtime booted from the same plan without lowered statements returns", async () => {
    const plain = await boot(stripped, d1b);
    const { runtime } = await boot(lowered, await LocalD1.create());
    expect(plain.runtime.bootReport().lowered).toBe("absent");
    // ids are generated by the statement (a random one per database), so rows compare with them masked
    const rows = async (r, call) => JSON.stringify(await call(r)).replace(/[0-9a-f]{32}/g, "<id>");
    for (const [name, call] of CALLS) expect(await rows(runtime, call), name).toBe(await rows(plain.runtime, call));
  });

  it("the same plan stripped of lowered statements compiles on first use, so the counters measure something", async () => {
    const { runtime, check } = await boot(stripped, await LocalD1.create());
    reset(check);
    await runtime.store.as(anonymous).view("shelf");
    expect(counters(check).check).toBeGreaterThan(0);
    expect(counters(check).applyPolicy).toBeGreaterThan(0);
    expect(counters(check).print).toBeGreaterThan(0);
  });
});
