import {
  RESERVED_ENTRY_COLUMNS,
  type JsonSchema,
  type ReservedEntryColumn,
} from "../domain/model/ManifestGrammar.js";
import type { EmitTypesRequest } from "./dto/EmitTypesRequest.js";
import type { EmitTypesResponse } from "./dto/EmitTypesResponse.js";

/**
 * Generate TypeScript declarations from v0.1 manifests:
 *   - Schema → Entry_<name> data shape
 *   - Procedure → ProcInput_<name> / ProcOutput_<name>
 *   - View → ViewParams_<name> / ViewRow_<name>
 *
 * Covers v0.1 JsonSchema features (string / integer / number /
 * boolean / object / array / enum / required / items). Skips $ref /
 * oneOf / anyOf / allOf / if-then-else — none in v0.1 grammar; they
 * fall through to `unknown`.
 *
 * Pure: no I/O. CLI handles stdout.
 */
const RESERVED_COLUMN_TYPES: Record<ReservedEntryColumn, string> = {
  id: "string",
  status: `"draft" | "published" | "archived"`,
  version: "number",
  createdAt: "number",
  updatedAt: "number",
  authorId: "string | null",
};

export class EmitTypesUseCase {
  execute(request: EmitTypesRequest): EmitTypesResponse {
    const schemas = request.linked.schemas.map((entry) => entry.manifest);
    const procedures = request.linked.procedures.map((entry) => entry.manifest);
    const views = request.linked.views.map((entry) => entry.manifest);
    const schemaByName = new Map(schemas.map((s) => [s.metadata.name, s]));

    const out: string[] = [];
    out.push(`// Generated by \`mantle-spec emit-types\`. Do not edit by hand.`);
    out.push("");
    out.push(`export namespace ${request.namespace} {`);
    out.push("");

    for (const s of schemas) {
      out.push(`  /** Entry data for Schema '${docText(s.metadata.name)}' */`);
      out.push(declLine(`Entry_${manifestTypeIdentifier(s.metadata.name)}`, s.spec.schema));
      out.push("");
    }

    for (const p of procedures) {
      out.push(`  /** Procedure '${docText(p.metadata.name)}' input */`);
      out.push(declLine(`ProcInput_${manifestTypeIdentifier(p.metadata.name)}`, p.spec.input));
      out.push("");
      out.push(`  /** Procedure '${docText(p.metadata.name)}' output */`);
      out.push(declLine(`ProcOutput_${manifestTypeIdentifier(p.metadata.name)}`, p.spec.output));
      out.push("");
    }

    for (const v of views) {
      const parent = v.spec.from ? schemaByName.get(v.spec.from) : undefined;
      if (v.spec.params) {
        out.push(`  /** Parameters accepted by View '${docText(v.metadata.name)}' */`);
        out.push(
          `  export type ViewParams_${manifestTypeIdentifier(v.metadata.name)} = ${renderType(v.spec.params, "  ")};`,
        );
        out.push("");
      }
      out.push(`  /** Row shape returned by View '${docText(v.metadata.name)}' */`);
      if (!parent) {
        out.push(`  export type ViewRow_${manifestTypeIdentifier(v.metadata.name)} = unknown;`);
      } else {
        const props = (parent.spec.schema.properties ?? {}) as Record<string, JsonSchema>;
        const fields = v.spec.fields ?? [...RESERVED_ENTRY_COLUMNS, ...Object.keys(props)];
        const reservedSet = new Set<string>(RESERVED_ENTRY_COLUMNS);
        const rendered: string[] = [];
        for (const f of fields) {
          if (reservedSet.has(f)) {
            rendered.push(`    ${f}: ${RESERVED_COLUMN_TYPES[f as ReservedEntryColumn]};`);
          } else if (props[f]) {
            rendered.push(`    ${f}?: ${renderTypeInline(props[f]!)};`);
          } else {
            rendered.push(`    ${f}?: unknown;`);
          }
        }
        out.push(`  export interface ViewRow_${manifestTypeIdentifier(v.metadata.name)} {`);
        out.push(...rendered);
        out.push(`  }`);
      }
      out.push("");
    }

    out.push(`}`);
    return { source: out.join("\n") + "\n" };
  }

  static run(request: EmitTypesRequest): EmitTypesResponse {
    return new EmitTypesUseCase().execute(request);
  }
}

export function manifestTypeIdentifier(name: string): string {
  const identifier = name.replace(/[^a-zA-Z0-9_$]+/g, "_");
  return /^[A-Za-z_$]/.test(identifier) ? identifier : `_${identifier}`;
}

function docText(value: string): string {
  return value.replaceAll("*/", "*\\/").replace(/[\r\n]+/g, " ");
}

/**
 * Emit a top-level declaration. Object schemas become an `interface`
 * (with a brace body); any non-object top-level (array / primitive /
 * union / enum) becomes a `type` alias — `interface X string[]` is a
 * TypeScript syntax error that would silently break the consumer's
 * generated .d.ts. (#394)
 */
function declLine(name: string, schema: JsonSchema): string {
  if (schema.type === "object") {
    return `  export interface ${name} ${renderType(schema, "  ")}`;
  }
  return `  export type ${name} = ${renderTypeInline(schema)};`;
}

function renderType(schema: JsonSchema, indent: string): string {
  if (schema.type === "object") {
    const props = (schema.properties ?? {}) as Record<string, JsonSchema>;
    const required = new Set(schema.required ?? []);
    const lines: string[] = ["{"];
    for (const [name, sub] of Object.entries(props)) {
      const optional = required.has(name) ? "" : "?";
      lines.push(`${indent}  ${tsKey(name)}${optional}: ${renderTypeInline(sub)};`);
    }
    lines.push(`${indent}}`);
    return lines.join("\n");
  }
  return renderTypeInline(schema);
}

function renderTypeInline(schema: JsonSchema): string {
  const t = schema.type;
  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    return schema.enum
      .map((v) => (typeof v === "string" ? JSON.stringify(v) : String(v)))
      .join(" | ");
  }
  if (Array.isArray(t)) {
    return t.map((kind) => primitiveType(kind, schema)).join(" | ");
  }
  if (t === "object") {
    return renderType(schema, "");
  }
  if (t === "array") {
    const items = schema.items ? renderTypeInline(schema.items) : "unknown";
    return `${items}[]`;
  }
  return primitiveType(typeof t === "string" ? t : "unknown", schema);
}

function primitiveType(t: string, schema: JsonSchema): string {
  switch (t) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    default:
      return schema.nullable === true ? "unknown | null" : "unknown";
  }
}

function tsKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}
