import {
  RESERVED_ENTRY_COLUMNS,
  type JsonSchema,
  type ReservedEntryColumn,
} from "../domain/model/ManifestGrammar.js";
import type { EmitTypesRequest } from "./dto/EmitTypesRequest.js";
import type { EmitTypesResponse } from "./dto/EmitTypesResponse.js";

/**
 * Generate TypeScript declarations from v0.1 manifests:
 *   - Schema → Entry_<name> data shape
 *   - Procedure → ProcInput_<name> / ProcOutput_<name>
 *   - View → ViewParams_<name> / ViewRow_<name>
 *
 * Covers Mantle's supported JSON Schema subset, including local `$defs`
 * refs, recursive definitions, `oneOf`, `const`, and dictionaries.
 *
 * Pure: no I/O. CLI handles stdout.
 */
const RESERVED_COLUMN_TYPES: Record<ReservedEntryColumn, string> = {
  id: "string",
  status: `"draft" | "published" | "archived"`,
  version: "number",
  createdAt: "number",
  updatedAt: "number",
  authorId: "string | null",
};

export class EmitTypesUseCase {
  execute(request: EmitTypesRequest): EmitTypesResponse {
    const schemas = request.linked.schemas.map((entry) => entry.manifest);
    const procedures = request.linked.procedures.map((entry) => entry.manifest);
    const views = request.linked.views.map((entry) => entry.manifest);
    const schemaByName = new Map(schemas.map((s) => [s.metadata.name, s]));

    const out: string[] = [];
    out.push(`// Generated by \`mantle-spec emit-types\`. Do not edit by hand.`);
    out.push("");
    out.push(`export namespace ${request.namespace} {`);
    out.push("");

    for (const s of schemas) {
      out.push(`  /** Entry data for Schema '${docText(s.metadata.name)}' */`);
      out.push(...declarationLines(`Entry_${manifestTypeIdentifier(s.metadata.name)}`, s.spec.schema));
      out.push("");
    }

    for (const p of procedures) {
      out.push(`  /** Procedure '${docText(p.metadata.name)}' input */`);
      out.push(...declarationLines(`ProcInput_${manifestTypeIdentifier(p.metadata.name)}`, p.spec.input));
      out.push("");
      out.push(`  /** Procedure '${docText(p.metadata.name)}' output */`);
      out.push(...declarationLines(`ProcOutput_${manifestTypeIdentifier(p.metadata.name)}`, p.spec.output));
      out.push("");
    }

    for (const v of views) {
      const parent = v.spec.from ? schemaByName.get(v.spec.from) : undefined;
      if (v.spec.params) {
        out.push(`  /** Parameters accepted by View '${docText(v.metadata.name)}' */`);
        out.push(
          ...declarationLines(`ViewParams_${manifestTypeIdentifier(v.metadata.name)}`, v.spec.params, false),
        );
        out.push("");
      }
      out.push(`  /** Row shape returned by View '${docText(v.metadata.name)}' */`);
      if (!parent) {
        out.push(`  export type ViewRow_${manifestTypeIdentifier(v.metadata.name)} = unknown;`);
      } else {
        const rootSchema = parent.spec.schema;
        const props = (rootSchema.properties ?? {}) as Record<string, JsonSchema>;
        const context = renderContext(`Entry_${manifestTypeIdentifier(parent.metadata.name)}`, rootSchema);
        const fields = v.spec.fields ?? [...RESERVED_ENTRY_COLUMNS, ...Object.keys(props)];
        const reservedSet = new Set<string>(RESERVED_ENTRY_COLUMNS);
        const rendered: string[] = [];
        for (const f of fields) {
          if (reservedSet.has(f)) {
            rendered.push(`    ${f}: ${RESERVED_COLUMN_TYPES[f as ReservedEntryColumn]};`);
          } else if (props[f]) {
            rendered.push(`    ${f}?: ${renderTypeInline(props[f]!, context)};`);
          } else {
            rendered.push(`    ${f}?: unknown;`);
          }
        }
        out.push(`  export interface ViewRow_${manifestTypeIdentifier(v.metadata.name)} {`);
        out.push(...rendered);
        out.push(`  }`);
      }
      out.push("");
    }

    out.push(`}`);
    return { source: out.join("\n") + "\n" };
  }

  static run(request: EmitTypesRequest): EmitTypesResponse {
    return new EmitTypesUseCase().execute(request);
  }
}

export function manifestTypeIdentifier(name: string): string {
  const identifier = name.replace(/[^a-zA-Z0-9_$]+/g, "_");
  return /^[A-Za-z_$]/.test(identifier) ? identifier : `_${identifier}`;
}

function docText(value: string): string {
  return value.replaceAll("*/", "*\\/").replace(/[\r\n]+/g, " ");
}

/**
 * Emit a top-level declaration. Object schemas become an `interface`
 * (with a brace body); any non-object top-level (array / primitive /
 * union / enum) becomes a `type` alias — `interface X string[]` is a
 * TypeScript syntax error that would silently break the consumer's
 * generated .d.ts. (#394)
 */
interface RenderContext {
  readonly root: JsonSchema;
  readonly definitionNames: ReadonlyMap<string, string>;
}

function renderContext(name: string, schema: JsonSchema): RenderContext {
  return {
    root: schema,
    definitionNames: new Map(
      Object.keys(schema.$defs ?? {}).map((definition) => [
        definition,
        `${name}_${manifestTypeIdentifier(definition)}`,
      ]),
    ),
  };
}

function declarationLines(name: string, schema: JsonSchema, preferInterface = true): string[] {
  const context = renderContext(name, schema);
  const lines = Object.entries(schema.$defs ?? {}).map(([definition, child]) =>
    declLine(context.definitionNames.get(definition)!, child, context),
  );
  lines.push(declLine(name, schema, context, preferInterface));
  return lines;
}

function declLine(name: string, schema: JsonSchema, context: RenderContext, preferInterface = true): string {
  if (preferInterface && schema.type === "object" && typeof schema.additionalProperties !== "object") {
    return `  export interface ${name} ${renderType(schema, "  ", context)}`;
  }
  return `  export type ${name} = ${renderTypeInline(schema, context)};`;
}

function renderType(schema: JsonSchema, indent: string, context: RenderContext): string {
  if (schema.type === "object") {
    const props = (schema.properties ?? {}) as Record<string, JsonSchema>;
    if (Object.keys(props).length === 0 && typeof schema.additionalProperties === "object") {
      return `Record<string, ${renderTypeInline(schema.additionalProperties, context)}>`;
    }
    const required = new Set(schema.required ?? []);
    const lines: string[] = ["{"];
    for (const [name, sub] of Object.entries(props)) {
      const optional = required.has(name) ? "" : "?";
      lines.push(`${indent}  ${tsKey(name)}${optional}: ${renderTypeInline(sub, context)};`);
    }
    if (schema.additionalProperties !== false) {
      if (typeof schema.additionalProperties === "object") {
        const values = Object.values(props).map((sub) => renderTypeInline(sub, context));
        if (Object.keys(props).some((name) => !required.has(name))) values.push("undefined");
        values.push(renderTypeInline(schema.additionalProperties, context));
        lines.push(`${indent}  [key: string]: ${[...new Set(values)].join(" | ")};`);
      } else {
        lines.push(`${indent}  [key: string]: unknown;`);
      }
    }
    lines.push(`${indent}}`);
    return lines.join("\n");
  }
  return renderTypeInline(schema, context);
}

function renderTypeInline(schema: JsonSchema, context: RenderContext): string {
  if (schema.$ref) return withNullable(renderRef(schema.$ref, context), schema);
  if (schema.oneOf?.length) {
    return withNullable(schema.oneOf.map((variant) => renderTypeInline(variant, context)).join(" | "), schema);
  }
  if ("const" in schema) return withNullable(JSON.stringify(schema.const), schema);
  const t = schema.type;
  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    return withNullable(schema.enum.map((value) => JSON.stringify(value)).join(" | "), schema);
  }
  if (Array.isArray(t)) {
    return withNullable(t.map((kind) => primitiveType(kind)).join(" | "), schema);
  }
  if (t === "object") {
    return withNullable(renderType(schema, "", context), schema);
  }
  if (t === "array") {
    const items = schema.items ? renderTypeInline(schema.items, context) : "unknown";
    return withNullable(`${items.includes(" | ") ? `(${items})` : items}[]`, schema);
  }
  return withNullable(primitiveType(typeof t === "string" ? t : "unknown"), schema);
}

function primitiveType(t: string): string {
  switch (t) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    default:
      return "unknown";
  }
}

function withNullable(rendered: string, schema: JsonSchema): string {
  return schema.nullable === true && !rendered.split(" | ").includes("null")
    ? `${rendered} | null`
    : rendered;
}

function renderRef(ref: string, context: RenderContext): string {
  let tokens: string[];
  try {
    tokens = decodeURIComponent(ref.slice(2)).split("/")
      .map((token) => token.replace(/~1/g, "/").replace(/~0/g, "~"));
  } catch {
    return "never";
  }
  const directDefinition = tokens.length === 2 && tokens[0] === "$defs"
    ? context.definitionNames.get(tokens[1]!)
    : undefined;
  if (directDefinition) return directDefinition;
  let current: unknown = context.root;
  for (const token of tokens) {
    current = current && typeof current === "object" && Object.prototype.hasOwnProperty.call(current, token)
      ? (current as Record<string, unknown>)[token]
      : undefined;
  }
  return current && typeof current === "object" && !Array.isArray(current)
    ? renderTypeInline(current as JsonSchema, context)
    : "never";
}

function tsKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}
