/** Shared typography for Markdown preview and the HTML WYSIWYG surface. */
export const RICH_CONTENT_CLASS = [
  "max-w-none space-y-3 text-sm leading-6 text-foreground",
  "[&_h1]:text-2xl [&_h1]:font-semibold",
  "[&_h2]:text-xl [&_h2]:font-semibold",
  "[&_h3]:text-lg [&_h3]:font-semibold",
  "[&_h4]:text-base [&_h4]:font-semibold",
  "[&_p]:whitespace-pre-wrap",
  "[&_ul]:list-disc [&_ul]:pl-5",
  "[&_ol]:list-decimal [&_ol]:pl-5",
  "[&_blockquote]:border-l-2 [&_blockquote]:border-border [&_blockquote]:pl-3 [&_blockquote]:text-muted-foreground",
  "[&_pre]:overflow-x-auto [&_pre]:rounded-md [&_pre]:bg-muted [&_pre]:p-3",
  "[&_code]:rounded-sm [&_code]:bg-muted [&_code]:px-1 [&_code]:font-mono [&_code]:text-[0.85em]",
  "[&_pre_code]:bg-transparent [&_pre_code]:p-0",
  "[&_a]:underline",
  "[&_img]:max-w-full",
  "[&_table]:w-full [&_table]:border-collapse",
  "[&_th]:border [&_th]:border-border [&_th]:px-2 [&_th]:py-1",
  "[&_td]:border [&_td]:border-border [&_td]:px-2 [&_td]:py-1",
  "[&_iframe]:aspect-video [&_iframe]:w-full",
].join(" ");
