export * from "./callerResolver.js";
export * from "./createAuthRoutes.js";
export { STAFF_ROLES, STAFF_ROLE_SET, decodeMemberCursor, encodeMemberCursor } from "./types.js";
export type { AuthMethodConfig, AuthMethodInfo, AuthSessionCache, AuthUserInfo, BootstrapOwnerRule, CreateMantleAuthOptions, CrossSubDomainCookiesConfig, InviteUserResult, LinkedAccountInfo, ListMembersArgs, MantleAuth, MantleAuthRequestContext, MemberListResult, MemberUserInfo, OAuthAccessTokenVerification, OAuthConsentInfo, OAuthConsentRequest, OAuthProviderConfig, OAuthProviderExtension, ProviderAccessToken, RegisterOAuthClientInput, RegisteredOAuthClient, SocialProviderId, StaffRole, StaffUserInfo } from "./types.js";
export { buildGenericOAuthProviders, buildOAuthProviderOptions, buildSocialProviders, buildTrustedOriginsFor, guardGithubLoginProfile, hasEmailAuthSurface, hashEmailOtp, normalizeAuthBasePath, normalizeAuthResponseCookies, pickLocale, resolveClientIpHeaders, shouldPromoteToOwner, validateBootstrap } from "./methods.js";
export { createSetupIncompleteAuth, isSetupIncompleteAuth } from "./setupIncomplete.js";
export type { SetupIncompleteAuthOptions } from "./setupIncomplete.js";
export { getProviderAccessTokenForRequest, mapRegisteredOAuthClient, verifyOAuthJwt, verifyOAuthJwtWithLocalJwks } from "./oauthTokens.js";
export { createMantleAuth } from "./createMantleAuth.js";
export { ConsoleEmailSender } from "./ConsoleEmailSender.js";
export { appleClientSecret, type AppleClientSecretArgs } from "./appleClientSecret.js";
